// A tiny dependency-free raster + PNG encoder, so the pixel art is generated by
// code committed to the repo rather than dropped in as opaque binaries. Uses
// only node:zlib. RGBA8, alpha-composited.

import { deflateSync } from "node:zlib";

const CRC = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const typeBuf = Buffer.from(type, "ascii");
  const body = Buffer.concat([typeBuf, data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body), 0);
  return Buffer.concat([len, body, crc]);
}

/** Parse "#rrggbb" or "#rrggbbaa" to [r,g,b,a]. */
export function hx(s) {
  const h = s.replace("#", "");
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  const a = h.length >= 8 ? parseInt(h.slice(6, 8), 16) : 255;
  return [r, g, b, a];
}

export class Canvas {
  constructor(w, h) {
    this.w = w;
    this.h = h;
    this.d = new Uint8Array(w * h * 4);
  }

  set(x, y, c) {
    x |= 0;
    y |= 0;
    if (x < 0 || y < 0 || x >= this.w || y >= this.h) return;
    const a = (c[3] ?? 255) / 255;
    if (a <= 0) return;
    const i = (y * this.w + x) * 4;
    if (a >= 1) {
      this.d[i] = c[0];
      this.d[i + 1] = c[1];
      this.d[i + 2] = c[2];
      this.d[i + 3] = 255;
      return;
    }
    const da = this.d[i + 3] / 255;
    const oa = a + da * (1 - a);
    const blend = (src, dst) =>
      oa === 0 ? 0 : Math.round((src * a + dst * da * (1 - a)) / oa);
    this.d[i] = blend(c[0], this.d[i]);
    this.d[i + 1] = blend(c[1], this.d[i + 1]);
    this.d[i + 2] = blend(c[2], this.d[i + 2]);
    this.d[i + 3] = Math.round(oa * 255);
  }

  rect(x, y, w, h, c) {
    for (let j = 0; j < h; j++) for (let i = 0; i < w; i++) this.set(x + i, y + j, c);
  }

  hline(x, y, w, c) {
    for (let i = 0; i < w; i++) this.set(x + i, y, c);
  }

  vline(x, y, h, c) {
    for (let j = 0; j < h; j++) this.set(x, y + j, c);
  }

  // Filled circle/ellipse, handy for spotlight pools and heads.
  ellipse(cx, cy, rx, ry, c) {
    for (let y = -ry; y <= ry; y++) {
      for (let x = -rx; x <= rx; x++) {
        if ((x * x) / (rx * rx) + (y * y) / (ry * ry) <= 1) this.set(cx + x, cy + y, c);
      }
    }
  }

  /** Stamp a pixel-map (array of equal-length strings) using a palette that
   *  maps each char to a color; "." and " " are transparent. `scale` enlarges
   *  each source pixel to a scale x scale block. */
  stamp(x, y, map, pal, scale = 1) {
    for (let ry = 0; ry < map.length; ry++) {
      const row = map[ry];
      for (let rx = 0; rx < row.length; rx++) {
        const ch = row[rx];
        if (ch === "." || ch === " ") continue;
        const c = pal[ch];
        if (!c) continue;
        this.rect(x + rx * scale, y + ry * scale, scale, scale, c);
      }
    }
  }

  encodePNG() {
    const { w, h, d } = this;
    const stride = w * 4;
    const raw = Buffer.alloc((stride + 1) * h);
    for (let y = 0; y < h; y++) {
      raw[y * (stride + 1)] = 0; // filter: none
      Buffer.from(d.buffer, y * stride, stride).copy(raw, y * (stride + 1) + 1);
    }
    const ihdr = Buffer.alloc(13);
    ihdr.writeUInt32BE(w, 0);
    ihdr.writeUInt32BE(h, 4);
    ihdr[8] = 8; // bit depth
    ihdr[9] = 6; // colour type RGBA
    const sig = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
    return Buffer.concat([
      sig,
      chunk("IHDR", ihdr),
      chunk("IDAT", deflateSync(raw, { level: 9 })),
      chunk("IEND", Buffer.alloc(0)),
    ]);
  }
}
